### ISSUE TITLE
server template

### ISSUE THREAD

**Issue by oodvg** [KevinTrinh1227/Hycord-Bot#8]
Am i able to get a server template you used in the setup video?

Thanks,
ooDVG

**Comment by KevinTrinh1227** [comment]
Hello,

Yes, you absolutely can! I do want to mention that using any version of older version of Hycord is unsupported, meaning that if you run into a lot of issues, I will not be able to offer as much support.

I highly recommend using the lastest release OR dev version (w latest commits) for newer features, and patched bugs. The version you are requesting is very outdated, although it should work fine. 

Note that if there are certain aspects of the older versions that you like, that I changed in the newer versions, you can always make another issue ticket requesting the code for the old features, and I can do it for you. Or a faster way is you're familiar with github, is searing through that features past commits and seeing the chances. 

Below I have attached a .zip file of the bot at relative to when that video was made. If you have any questions feel free to reach out! 

[Hycord-Bot-0.1.0.zip](https://github.com/KevinTrinh1227/Hycord-Bot/files/13255740/Hycord-Bot-0.1.0.zip)

**Comment by oodvg** [comment]
Oh sorry for the confusion! I was talking about a discord server template.

**Comment by KevinTrinh1227** [comment]
No worries!

Here is a link to the template: https://discord.new/pdxrqAApR9Ee

**Comment by oodvg** [comment]
Thank you!
